### ISSUE TITLE
博客系统需求

### ISSUE THREAD

**Issue by daweilv** [code4funlnyx/lnyx#1]
支持多人
登录注册
博客welcome页、分类页、文章详情页
后端用户注册、登录、用户管理

Front end UI for reference
https://75076dfbc6608dd589368ab520ce7bf918dc11a2.googledrive.com/host/0Bxbofwq0kd4RfkJZSExIUHBBeVZncEtfQ2lSajBxV2FHRVJEMnBaUGFmRFhmTWJmbGliaHc/
http://www.15yan.com/topic/xiao-duan-de-gu-shi/

base on nodejs express/ bootstrap
express en(better) http://expressjs.com/en/starter/hello-world.html
express cn http://expressjs.jser.us/3x_zh-cn/api.html
bootstrap en(better) http://getbootstrap.com/
bootstrap cn http://v3.bootcss.com/

**Comment by code4funlnyx** [comment]
前端UI参考：https://75076dfbc6608dd589368ab520ce7bf918dc11a2.googledrive.com/host/0Bxbofwq0kd4RfkJZSExIUHBBeVZncEtfQ2lSajBxV2FHRVJEMnBaUGFmRFhmTWJmbGliaHc/
http://www.15yan.com/topic/xiao-duan-de-gu-shi/

**Comment by code4funlnyx** [comment]
base on nodejs express/ bootstrap
express en(prefer) http://expressjs.com/en/starter/hello-world.html
express cn http://expressjs.jser.us/3x_zh-cn/api.html
bootstrap en http://getbootstrap.com/
bootstrap cn http://v3.bootcss.com/

**Comment by daweilv** [comment]
move to wiki
